# The exact path to the Singapore cloud server
spring.datasource.url=jdbc:postgresql://ep-shy-dream-a1xdmvo8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# Your Neon database credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_u69MhQtDvaUI

# The magic command that builds the tables automatically
spring.jpa.hibernate.ddl-auto=update